services:
  postgres:
    image: postgres:16
    container_name: pg_snowflake_cdc
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  generator:
    build: ./generator
    container_name: orders_generator
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      RATE_PER_SECOND: "2"
    depends_on:
      - postgres
